### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by reidmefirst** [joshualouden/RaspberryPiBox#2]
I'm having trouble determining if this project is compatible with the Raspberry Pi 4 Model B? It would be helpful to know if it works with the the 4gb or 8gb models. Thanks in advance!

**Comment by joshualouden** [comment]
We're going through testing now, and should have it updated soon.

**Comment by joshualouden** [comment]
This has been updated to be compatible with Raspberry Pi 4.
